apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: crm-system
  labels:
    app: postgres-backup
    tier: database
spec:
  schedule: "0 2 * * *" # Daily at 2 AM
  timeZone: "UTC"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: postgres-backup
            tier: database
        spec:
          restartPolicy: OnFailure
          containers:
          - name: postgres-backup
            image: postgres:16-alpine
            command:
            - /bin/sh
            - -c
            - |
              BACKUP_FILE="/backup/crm-backup-$(date +%Y%m%d-%H%M%S).sql"
              pg_dump $DATABASE_URL > $BACKUP_FILE
              if [ $? -eq 0 ]; then
                echo "Backup successful: $BACKUP_FILE"
                # Upload to cloud storage (AWS S3, GCS, etc.)
                aws s3 cp $BACKUP_FILE s3://your-backup-bucket/postgres-backups/
                # Keep only last 7 days locally
                find /backup -name "crm-backup-*.sql" -mtime +7 -delete
              else
                echo "Backup failed"
                exit 1
              fi
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DATABASE_URL
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: aws_secret_access_key
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "256Mi"
                cpu: "200m"
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: backup-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  namespace: crm-system
  labels:
    app: postgres-backup
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 50Gi