apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crm-prod-secrets
  namespace: crm-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: crm-secrets
    creationPolicy: Owner
  data:
  - secretKey: SESSION_SECRET
    remoteRef:
      key: crm/prod
      property: session_secret
  - secretKey: JWT_SECRET
    remoteRef:
      key: crm/prod
      property: jwt_secret
  - secretKey: DATABASE_URL
    remoteRef:
      key: crm/prod
      property: database_url

---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: crm-system
spec:
  provider:
    vault:
      server: "https://vault.yourcompany.com"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "crm-role"
          serviceAccountRef:
            name: "crm-service-account"