apiVersion: v1
kind: ConfigMap
metadata:
  name: crm-config
  namespace: crm-system
  labels:
    app: crm-app
    tier: backend
data:
  NODE_ENV: "production"
  PORT: "5000"
  LOG_LEVEL: "info"
  CORS_ORIGIN: "*"
  SESSION_NAME: "crm_session"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: crm-system
  labels:
    app: postgres
    tier: database
data:
  POSTGRES_DB: "crm_db"
  POSTGRES_USER: "crm_user"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: crm-system
  labels:
    app: nginx
    tier: proxy
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream app {
            server crm-app-service:5000;
        }
        
        server {
            listen 80;
            server_name _;
            
            location /health {
                access_log off;
                proxy_pass http://app;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
            
            location / {
                proxy_pass http://app;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }