apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: crm-base
  
resources:
- namespace.yaml
- configmap.yaml
- secrets.yaml
- postgres-pvc.yaml
- postgres-deployment.yaml
- postgres-service.yaml
- app-deployment.yaml
- app-service.yaml
- hpa.yaml
- ingress.yaml
- monitoring.yaml
- rbac.yaml

commonLabels:
  app.kubernetes.io/name: crm
  app.kubernetes.io/version: "1.0.0"

images:
- name: crm-app
  newName: registry.yourcompany.com/crm-app
  newTag: latest