apiVersion: v1
kind: ServiceAccount
metadata:
  name: crm-service-account
  namespace: crm-system
  labels:
    app: crm-app

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: crm-system
  name: crm-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crm-role-binding
  namespace: crm-system
subjects:
- kind: ServiceAccount
  name: crm-service-account
  namespace: crm-system
roleRef:
  kind: Role
  name: crm-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: crm-app-pdb
  namespace: crm-system
  labels:
    app: crm-app
    tier: backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: crm-app
      tier: backend