apiVersion: v1
kind: Secret
metadata:
  name: crm-secrets
  namespace: crm-system
  labels:
    app: crm-app
    tier: backend
type: Opaque
stringData:
  SESSION_SECRET: "your-super-secret-session-key-change-in-production"
  JWT_SECRET: "your-super-secret-jwt-key-change-in-production"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: crm-system
  labels:
    app: postgres
    tier: database
type: Opaque
stringData:
  POSTGRES_PASSWORD: "secure-postgres-password-change-in-production"
  DATABASE_URL: "postgres://crm_user:secure-postgres-password-change-in-production@postgres-service:5432/crm_db"